// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCQLF6UdOaJiU8HIDE3YWTTKWaAegfWYo',
    appId: '1:757327945101:web:9c9f971c8a072e8e7131c4',
    messagingSenderId: '757327945101',
    projectId: 'ada-application',
    authDomain: 'ada-application.firebaseapp.com',
    storageBucket: 'ada-application.appspot.com',
    measurementId: 'G-W7QWR0KB2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKIEW7yfQmWVDUBVOWel9_uf6fVWI3fPM',
    appId: '1:757327945101:android:269b0c0c48c8dc3e7131c4',
    messagingSenderId: '757327945101',
    projectId: 'ada-application',
    storageBucket: 'ada-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9RcqaamlOLTBbwREHHed7onsPJYa0iuI',
    appId: '1:757327945101:ios:2401d56af35efcd17131c4',
    messagingSenderId: '757327945101',
    projectId: 'ada-application',
    storageBucket: 'ada-application.appspot.com',
    iosBundleId: 'com.kezign.adaBonusCustomer',
  );
}
